[project]
name = "app"
version = "0.1.0"
description = "Who Said This dependencies"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.124.0",
    "python-multipart>=0.0.20",
    "uvicorn[standard]>=0.38.0",
]
